\c sales;

-- Cadastramento de Produtos

INSERT INTO produtos (id, titulo, descricao, preco) VALUES 
(1, 'Cadeira Gamer', 'Cadeira confortável para fazer live', 1200.00),
(2, 'Iphone', 'Iphone 14', 2500.00),
(3, 'Iphone', 'Iphone 14', 2500.00),
(4, 'Notebook Dell', 'Notebook para trabalho e estudo', 3000.00),
(5, 'Smart TV 4K', 'TV com resolução 4K para uma experiência incrível', 2000.00),
(6, 'Fones de Ouvido Bluetooth', 'Fones sem fio para uma experiência auditiva livre', 150.00),
(7, 'Console de Videogame', 'Console para jogos de última geração', 500.00),
(8, 'Máquina de Café Automática', 'Prepara café delicioso com um toque', 400.00),
(9, 'Monitor UltraWide', 'Monitor expansivo para multitarefa eficiente', 600.00),
(10, 'Mouse Gamer', 'Mouse com sensor de alta precisão para jogos', 80.00),
(11, 'Teclado Mecânico RGB', 'Teclado mecânico com iluminação personalizável', 120.00),
(12, 'Aspirador de Pó Robô', 'Aspirador automático para facilitar a limpeza', 250.00),
(13, 'Caixa de Som Bluetooth', 'Caixa de som portátil para ouvir sua música favorita', 100.00),
(14, 'Impressora Multifuncional', 'Impressora que imprime, copia e digitaliza', 150.00),
(15, 'HD Externo 1TB', 'Armazenamento externo para backup e transporte de dados', 80.00),
(16, 'Câmera DSLR', 'Câmera profissional para capturar momentos especiais', 1200.00),
(17, 'Mesa de Escritório', 'Mesa espaçosa para um ambiente de trabalho confortável', 300.00),
(18, 'Bicicleta Ergométrica', 'Bicicleta para exercícios físicos em casa', 400.00),
(19, 'Secador de Cabelo Profissional', 'Secador potente para cuidados com o cabelo', 50.00),
(20, 'Mala de Viagem', 'Mala resistente e espaçosa para suas viagens', 70.00),
(21, 'Relógio Inteligente', 'Relógio com funções inteligentes e monitoramento de saúde', 200.00),
(22, 'Ventilador de Torre', 'Ventilador compacto para refrescar o ambiente', 60.00),
(23, 'Smartphone Android', 'Smartphone com sistema operacional Android', 800.00),
(24, 'Cadeira Ergonômica', 'Cadeira projetada para proporcionar conforto e suporte', 350.00),
(25, 'Cafeteira Programável', 'Cafeteira com programação para preparar café automaticamente', 120.00),
(26, 'Tablet 10 polegadas', 'Tablet para entretenimento e produtividade', 300.00),
(27, 'Luminária de Mesa LED', 'Luminária com iluminação LED ajustável', 40.00),
(28, 'HD SSD 500GB', 'Armazenamento SSD para alta velocidade de leitura e gravação', 100.00),
(29, 'Churrasqueira Elétrica', 'Churrasqueira para uso interno com controle de temperatura', 180.00),
(30, 'Máquina de Lavar Roupa', 'Máquina com múltiplos programas de lavagem', 600.00),
(31, 'Tênis Esportivo', 'Tênis confortável para prática de esportes', 80.00),
(32, 'Fogão a Gás', 'Fogão com queimadores a gás para cozimento rápido', 400.00),
(33, 'Caixa de Ferramentas', 'Caixa organizadora com diversas ferramentas', 50.00),
(34, 'Mochila para Laptop', 'Mochila resistente com compartimento acolchoado para laptop', 60.00),
(35, 'Panela Elétrica de Arroz', 'Panela elétrica para preparar arroz de forma prática', 45.00),
(36, 'Laptop Ultrafino', 'Laptop leve e portátil para uso diário', 900.00),
(37, 'Mini Geladeira', 'Geladeira compacta para bebidas e snacks', 120.00),
(38, 'Batedeira Planetária', 'Batedeira com múltiplas velocidades para preparo de receitas', 80.00),
(39, 'Fraldas Descartáveis', 'Pacote de fraldas para bebês', 30.00),
(40, 'Micro-ondas Digital', 'Micro-ondas com funções programáveis', 150.00),
(41, 'Cadeado Eletrônico', 'Cadeado com controle eletrônico para segurança', 20.00),
(42, 'Tapete Antiderrapante', 'Tapete para prevenir escorregões em áreas úmidas', 25.00);