FROM python:3.11

WORKDIR /app

RUN apt-get update && \
    apt-get install -y postgresql-client && \
    rm -rf /var/lib/apt/lists/*

COPY ./database /app

RUN pip install --upgrade pip && pip install -r requirements.txt

CMD ["python", "setup_database_script.py"]
