version: '3.8'

services:
  frontend:
    build: streamlit
    ports:
      - 8501:8501
    depends_on:
      - postgres
      - api
    volumes:
      - ./streamlit:/app
    restart: always
    networks:
      - app
    container_name: frontend

  postgres:
    image: postgres
    volumes:
      - ./database_test:/app
#      - ./database_test/01-table_produtos.sql:/docker-entrypoint-initdb.d/01-table_produtos.sql
#      - ./database_test/02-produtos.sql:/docker-entrypoint-initdb.d/02-produtos.sql
    environment:
      POSTGRES_PASSWORD: "minha_senha"
      POSTGRES_USER: "meu_usuario"
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app
    container_name: database

  api:
    build: api
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    restart: always
    networks:
      - app
    container_name: api

networks:
  app:
    driver: bridge